---
# Docker doc: https://docs.docker.com/engine/install/
- name: Docker | Install required packages
  become: yes
  apt:
    cache_valid_time: 3600
    state: present
    pkg:
      - curl
      - ca-certificates
      - gnupg
  register: packages_install

- name: Docker | Check for existing gpg key
  become: no
  stat:
    path: "/etc/apt/keyrings/docker.gpg"
  register: gpg_key
  when: packages_install is succeeded

- name: Docker | Add gpg key
  become: yes
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  when: not gpg_key.stat.exists

- name: Docker | Add repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable"
    filename: docker
    state: present
    update_cache: yes

- name: Docker | Install packages
  become: yes
  apt:
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Docker | Add the docker group to the user
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Docker | Check that docker is running
  become: yes
  service:
    name: docker
    enabled: yes
    state: started

- name: Docker | Install docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "/usr/local/bin/docker-compose"
    mode: 0755
