---
- name: PHP | Add repository
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
    filename: php
    state: present
    codename: focal

- name: PHP | Install php packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    state: present
    pkg:
      - php7.4-cli
      - php7.4-opcache
      - php7.4-common
      - php7.4-amqp
      - php7.4-curl
      - php7.4-fpm
      - php7.4-intl
      - php7.4-json
      - php7.4-mbstring
      - php7.4-pgsql
      - php7.4-mysql
      - php7.4-redis
      - php7.4-readline
      - php7.4-sqlite3
      - php7.4-xml
      - php7.4-xdebug
      - php7.4-zip
      - php8.0-cli
      - php8.0-opcache
      - php8.0-common
      - php8.0-amqp
      - php8.0-curl
      - php8.0-fpm
      - php8.0-intl
      - php8.0-mbstring
      - php8.0-pgsql
      - php8.0-mysql
      - php8.0-redis
      - php8.0-readline
      - php8.0-sqlite3
      - php8.0-xml
      - php8.0-xdebug
      - php8.0-zip
      - php8.1-cli
      - php8.1-opcache
      - php8.1-common
      - php8.1-amqp
      - php8.1-curl
      - php8.1-fpm
      - php8.1-intl
      - php8.1-mbstring
      - php8.1-pgsql
      - php8.1-mysql
      - php8.1-redis
      - php8.1-readline
      - php8.1-sqlite3
      - php8.1-xml
      - php8.1-xdebug
      - php8.1-zip

- name: PHP | Write /etc/php/{{ item }}/conf.d/99-custom.ini file
  become: yes
  copy:
    dest: /etc/php/{{ item }}/conf.d/99-custom.ini
    content: |
      [PHP]
      error_reporting = E_ALL
      display_errors = On
      display_startup_errors = On
      log_errors = Off
      #log_errors_max_len = 1024
      report_memleaks = On
      default_charset = "UTF-8"
      #auto_prepend_file = ${HOME}/.composer/vendor/autoload.php
      [Date]
      date.timezone = Europe/Paris
  with_items:
    - 7.4/cli
    - 7.4/fpm
    - 8.0/cli
    - 8.0/fpm
    - 8.1/cli
    - 8.1/fpm

- name: PHP | Configure the default version
  become: yes
  alternatives:
    name: php
    path: /usr/bin/php8.1

- name: PHP | Disable xdebug
  become: yes
  shell: phpdismod xdebug
